# Generated by Django 3.0.5 on 2020-04-26 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='qty',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_qty',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='qty',
            field=models.IntegerField(default=0),
        ),
    ]
